import 'dart:async';

import 'package:flutter/material.dart';

import '../models/market_price_models.dart';

class MarketPriceService {
  const MarketPriceService();

  Future<MarketSnapshot> fetchSnapshot({
    required String locationLabel,
    double? latitude,
    double? longitude,
  }) async {
    await Future<void>.delayed(const Duration(milliseconds: 450));
    final userLatitude = latitude ?? 20.9674;
    final userLongitude = longitude ?? -89.5926;
    final nearbyMarkets = [..._markets]
      ..sort((a, b) {
        final distanceA = a.distanceKmFrom(userLatitude, userLongitude);
        final distanceB = b.distanceKmFrom(userLatitude, userLongitude);
        return distanceA.compareTo(distanceB);
      });
    final nearestMarket = nearbyMarkets.first;
    final prices = _buildReferencePrices()
      ..sort((a, b) {
        final distanceA = a.market.distanceKmFrom(userLatitude, userLongitude);
        final distanceB = b.market.distanceKmFrom(userLatitude, userLongitude);
        return distanceA.compareTo(distanceB);
      });

    return MarketSnapshot(
      prices: prices,
      nearbyMarkets: nearbyMarkets.take(5).toList(),
      nearestMarket: nearestMarket,
      locationLabel: locationLabel,
      isLiveSource: false,
    );
  }

  static final List<MarketCenter> _markets = <MarketCenter>[
    MarketCenter(
      id: 'merida',
      name: 'Central de Abasto de Mérida',
      state: 'Yucatán',
      city: 'Mérida',
      latitude: 20.9366,
      longitude: -89.6517,
      type: 'Central mayorista',
      address: 'Zona sur de Mérida, Yucatán',
      openingHours:
          'Lun 7:00-16:00; Mar 8:00-17:00; Mié 7:00-18:00; Jue 8:00-18:00; Vie-Sáb 8:00-17:00; Dom 9:00-15:00',
      phoneNumbers: const <String>['999 945 0605'],
      accessNotes: 'Acceso recomendado por vialidades principales de Mérida.',
      mainProducts: <String>[
        'cítricos',
        'papaya',
        'tomate',
        'chile habanero',
        'hortalizas',
      ],
    ),
    MarketCenter(
      id: 'oxkutzcab',
      name: 'Centro Mayorista Oxkutzcab',
      state: 'Yucatán',
      city: 'Oxkutzcab',
      latitude: 20.3023,
      longitude: -89.4181,
      type: 'Centro mayorista',
      address: 'Oxkutzcab, Yucatán',
      openingHours: 'Por confirmar',
      accessNotes: 'Ruta frecuente para cítricos y frutas del sur de Yucatán.',
      mainProducts: <String>[
        'limón',
        'naranja',
        'mango',
        'chile habanero',
        'calabaza',
      ],
    ),
    MarketCenter(
      id: 'casa_pueblo',
      name: 'Mercado Casa del Pueblo',
      state: 'Yucatán',
      city: 'Mérida',
      latitude: 20.9671,
      longitude: -89.6237,
      type: 'Mercado regional',
      address: 'Centro de Mérida, Yucatán',
      openingHours: 'Lun-Dom 7:00-17:00',
      accessNotes: 'Útil para ventas regionales y volumen moderado.',
      mainProducts: <String>[
        'maíz',
        'frijol',
        'hortalizas',
        'papaya',
        'sandía',
      ],
    ),
    MarketCenter(
      id: 'ticul',
      name: 'Mercado Agrícola de Ticul',
      state: 'Yucatán',
      city: 'Ticul',
      latitude: 20.3971,
      longitude: -89.5357,
      type: 'Mercado regional',
      address: 'Ticul, Yucatán',
      openingHours: 'Por confirmar',
      accessNotes: 'Punto regional para productores del sur del estado.',
      mainProducts: <String>['cítricos', 'chile', 'maíz', 'hortalizas'],
    ),
    MarketCenter(
      id: 'valladolid',
      name: 'Centro de Abasto Valladolid',
      state: 'Yucatán',
      city: 'Valladolid',
      latitude: 20.6896,
      longitude: -88.2022,
      type: 'Mercado regional',
      address: 'Valladolid, Yucatán',
      openingHours: 'Lun-Dom 5:00-17:00',
      phoneNumbers: const <String>['985 124 7464'],
      accessNotes: 'Opción cercana para productores del oriente de Yucatán.',
      mainProducts: <String>['maíz', 'frijol', 'papaya', 'sandía'],
    ),
    MarketCenter(
      id: 'cancun',
      name: 'Módulo de Abasto Cancún',
      state: 'Quintana Roo',
      city: 'Cancún',
      latitude: 21.1619,
      longitude: -86.8515,
      type: 'Módulo de abasto',
      address: 'Cancún, Quintana Roo',
      openingHours: 'Abierto 24 horas',
      phoneNumbers: const <String>['998 886 2080', '998 886 2180'],
      accessNotes: 'Centro de demanda turística para frutas y hortalizas.',
      mainProducts: <String>['papaya', 'limón', 'tomate', 'chile', 'frutas'],
    ),
    MarketCenter(
      id: 'chetumal',
      name: 'Mercado de Chetumal',
      state: 'Quintana Roo',
      city: 'Chetumal',
      latitude: 18.5001,
      longitude: -88.2961,
      type: 'Mercado mayorista',
      address: 'Chetumal, Quintana Roo',
      openingHours: 'Lun-Dom 6:30-18:00',
      accessNotes: 'Alternativa para el sur de Quintana Roo y zona fronteriza.',
      mainProducts: <String>['piña', 'papaya', 'limón', 'hortalizas'],
    ),
    MarketCenter(
      id: 'campeche',
      name: 'Mercado Pedro Sáinz de Baranda',
      state: 'Campeche',
      city: 'Campeche',
      latitude: 19.8454,
      longitude: -90.5233,
      type: 'Mercado mayorista',
      address: 'Campeche, Campeche',
      openingHours: 'Lun-Dom 5:00-22:00',
      phoneNumbers: const <String>['981 816 6313'],
      accessNotes: 'Punto regional para la península occidental.',
      mainProducts: <String>['mango', 'papaya', 'sandía', 'maíz'],
    ),
    MarketCenter(
      id: 'iztapalapa',
      name: 'Central de Abasto de Iztapalapa',
      state: 'Ciudad de México',
      city: 'Ciudad de México',
      latitude: 19.3732,
      longitude: -99.0914,
      type: 'Central nacional',
      address: 'Iztapalapa, Ciudad de México',
      openingHours: 'Abierto 24 horas',
      phoneNumbers: const <String>['55 5694 2137'],
      accessNotes: 'Central nacional con mayor exigencia logística.',
      mainProducts: <String>[
        'aguacate',
        'tomate',
        'limón',
        'granos',
        'hortalizas',
      ],
    ),
    MarketCenter(
      id: 'guadalajara',
      name: 'Mercado de Abasto de Guadalajara',
      state: 'Jalisco',
      city: 'Guadalajara',
      latitude: 20.6537,
      longitude: -103.3941,
      type: 'Central nacional',
      address: 'Guadalajara, Jalisco',
      openingHours: 'Lun-Dom 2:00-18:00',
      phoneNumbers: const <String>['55 4256 0081', '33 1201 8576'],
      accessNotes: 'Central nacional para occidente y rutas de alto volumen.',
      mainProducts: <String>['maíz', 'aguacate', 'tomate', 'frutas'],
    ),
    _regionalMarket(
      id: 'aguascalientes',
      city: 'Aguascalientes',
      state: 'Aguascalientes',
      latitude: 21.8853,
      longitude: -102.2916,
      products: <String>['maíz', 'frijol', 'chile', 'hortalizas'],
    ),
    _regionalMarket(
      id: 'mexicali',
      city: 'Mexicali',
      state: 'Baja California',
      latitude: 32.6245,
      longitude: -115.4523,
      products: <String>['trigo', 'algodón', 'hortalizas', 'cebolla'],
    ),
    _regionalMarket(
      id: 'la_paz',
      city: 'La Paz',
      state: 'Baja California Sur',
      latitude: 24.1426,
      longitude: -110.3128,
      products: <String>['tomate', 'chile', 'cebolla', 'frutas'],
    ),
    _regionalMarket(
      id: 'hopelchen',
      city: 'Hopelchén',
      state: 'Campeche',
      latitude: 19.7464,
      longitude: -89.8441,
      products: <String>['maíz', 'soja', 'sorgo', 'frijol'],
    ),
    _regionalMarket(
      id: 'tuxtla',
      city: 'Tuxtla Gutiérrez',
      state: 'Chiapas',
      latitude: 16.7516,
      longitude: -93.1029,
      products: <String>['café', 'maíz', 'plátano', 'frutas'],
    ),
    _regionalMarket(
      id: 'chihuahua',
      city: 'Chihuahua',
      state: 'Chihuahua',
      latitude: 28.6353,
      longitude: -106.0889,
      products: <String>['manzana', 'chile', 'maíz', 'frijol'],
    ),
    _regionalMarket(
      id: 'saltillo',
      city: 'Saltillo',
      state: 'Coahuila',
      latitude: 25.4232,
      longitude: -101.0053,
      products: <String>['maíz', 'sorgo', 'forrajes', 'hortalizas'],
    ),
    _regionalMarket(
      id: 'colima',
      city: 'Colima',
      state: 'Colima',
      latitude: 19.2433,
      longitude: -103.7241,
      products: <String>['limón', 'plátano', 'mango', 'papaya'],
    ),
    _regionalMarket(
      id: 'durango',
      city: 'Durango',
      state: 'Durango',
      latitude: 24.0277,
      longitude: -104.6532,
      products: <String>['frijol', 'maíz', 'chile', 'forrajes'],
    ),
    _regionalMarket(
      id: 'toluca',
      city: 'Toluca',
      state: 'Estado de México',
      latitude: 19.2826,
      longitude: -99.6557,
      products: <String>['papa', 'maíz', 'haba', 'hortalizas'],
    ),
    _regionalMarket(
      id: 'guanajuato',
      city: 'Guanajuato',
      state: 'Guanajuato',
      latitude: 21.0190,
      longitude: -101.2574,
      products: <String>['brócoli', 'lechuga', 'maíz', 'sorgo'],
    ),
    _regionalMarket(
      id: 'chilpancingo',
      city: 'Chilpancingo',
      state: 'Guerrero',
      latitude: 17.5515,
      longitude: -99.5006,
      products: <String>['mango', 'maíz', 'limón', 'chile'],
    ),
    _regionalMarket(
      id: 'pachuca',
      city: 'Pachuca',
      state: 'Hidalgo',
      latitude: 20.1011,
      longitude: -98.7591,
      products: <String>['cebada', 'maíz', 'nopal', 'hortalizas'],
    ),
    _regionalMarket(
      id: 'morelia',
      city: 'Morelia',
      state: 'Michoacán',
      latitude: 19.7008,
      longitude: -101.1844,
      products: <String>['aguacate', 'berries', 'maíz', 'limón'],
    ),
    _regionalMarket(
      id: 'cuernavaca',
      city: 'Cuernavaca',
      state: 'Morelos',
      latitude: 18.9242,
      longitude: -99.2216,
      products: <String>['jitomate', 'nopal', 'sorgo', 'flores'],
    ),
    _regionalMarket(
      id: 'tepic',
      city: 'Tepic',
      state: 'Nayarit',
      latitude: 21.5085,
      longitude: -104.8957,
      products: <String>['mango', 'plátano', 'maíz', 'frijol'],
    ),
    _regionalMarket(
      id: 'monterrey',
      city: 'Monterrey',
      state: 'Nuevo León',
      latitude: 25.6866,
      longitude: -100.3161,
      products: <String>['cítricos', 'maíz', 'hortalizas', 'frutas'],
    ),
    _regionalMarket(
      id: 'oaxaca',
      city: 'Oaxaca',
      state: 'Oaxaca',
      latitude: 17.0732,
      longitude: -96.7266,
      products: <String>['maíz', 'agave', 'café', 'frijol'],
    ),
    _regionalMarket(
      id: 'puebla',
      city: 'Puebla',
      state: 'Puebla',
      latitude: 19.0414,
      longitude: -98.2063,
      products: <String>['maíz', 'hortalizas', 'chile', 'frutas'],
    ),
    _regionalMarket(
      id: 'queretaro',
      city: 'Querétaro',
      state: 'Querétaro',
      latitude: 20.5888,
      longitude: -100.3899,
      products: <String>['maíz', 'sorgo', 'hortalizas', 'frutas'],
    ),
    _regionalMarket(
      id: 'san_luis_potosi',
      city: 'San Luis Potosí',
      state: 'San Luis Potosí',
      latitude: 22.1565,
      longitude: -100.9855,
      products: <String>['chile', 'tomate', 'maíz', 'frijol'],
    ),
    _regionalMarket(
      id: 'culiacan',
      city: 'Culiacán',
      state: 'Sinaloa',
      latitude: 24.8091,
      longitude: -107.3940,
      products: <String>['tomate', 'chile', 'maíz', 'hortalizas'],
    ),
    _regionalMarket(
      id: 'hermosillo',
      city: 'Hermosillo',
      state: 'Sonora',
      latitude: 29.0729,
      longitude: -110.9559,
      products: <String>['trigo', 'uva', 'naranja', 'hortalizas'],
    ),
    _regionalMarket(
      id: 'villahermosa',
      city: 'Villahermosa',
      state: 'Tabasco',
      latitude: 17.9892,
      longitude: -92.9475,
      products: <String>['cacao', 'plátano', 'maíz', 'papaya'],
    ),
    _regionalMarket(
      id: 'ciudad_victoria',
      city: 'Ciudad Victoria',
      state: 'Tamaulipas',
      latitude: 23.7369,
      longitude: -99.1411,
      products: <String>['sorgo', 'maíz', 'cítricos', 'hortalizas'],
    ),
    _regionalMarket(
      id: 'tlaxcala',
      city: 'Tlaxcala',
      state: 'Tlaxcala',
      latitude: 19.3182,
      longitude: -98.2375,
      products: <String>['maíz', 'trigo', 'cebada', 'hortalizas'],
    ),
    _regionalMarket(
      id: 'xalapa',
      city: 'Xalapa',
      state: 'Veracruz',
      latitude: 19.5438,
      longitude: -96.9102,
      products: <String>['café', 'cítricos', 'maíz', 'plátano'],
    ),
    _regionalMarket(
      id: 'tizimin',
      city: 'Tizimín',
      state: 'Yucatán',
      latitude: 21.1429,
      longitude: -88.1510,
      products: <String>['maíz', 'frijol', 'cítricos', 'forrajes'],
    ),
    _regionalMarket(
      id: 'izamal',
      city: 'Izamal',
      state: 'Yucatán',
      latitude: 20.9301,
      longitude: -89.0187,
      products: <String>['maíz', 'frijol', 'hortalizas', 'cítricos'],
    ),
    _regionalMarket(
      id: 'tekax',
      city: 'Tekax',
      state: 'Yucatán',
      latitude: 20.4614,
      longitude: -89.4325,
      products: <String>['cítricos', 'maíz', 'chile', 'mango'],
    ),
    _regionalMarket(
      id: 'motul',
      city: 'Motul',
      state: 'Yucatán',
      latitude: 21.0971,
      longitude: -89.2833,
      products: <String>['maíz', 'hortalizas', 'papaya', 'frijol'],
    ),
    _regionalMarket(
      id: 'zacatecas',
      city: 'Zacatecas',
      state: 'Zacatecas',
      latitude: 22.7709,
      longitude: -102.5832,
      products: <String>['frijol', 'chile', 'maíz', 'ajo'],
    ),
  ];

  static MarketCenter _regionalMarket({
    required String id,
    required String city,
    required String state,
    required double latitude,
    required double longitude,
    required List<String> products,
  }) {
    return MarketCenter(
      id: id,
      name: 'Mercado regional de $city',
      state: state,
      city: city,
      latitude: latitude,
      longitude: longitude,
      type: 'Mercado regional',
      address: '$city, $state',
      openingHours: 'Por confirmar',
      accessNotes: 'Punto de referencia regional para productores de $state.',
      mainProducts: products,
    );
  }

  static List<CropMarketPrice> _buildReferencePrices() {
    final now = DateTime.now();
    return <CropMarketPrice>[
      _price(
        cropId: 'limon',
        cropName: 'Limón',
        variety: 'sin semilla',
        market: _market('merida'),
        price: 25.8,
        day: 3.4,
        week: 8.1,
        presentation: 'Caja 18 kg',
        color: const Color(0xFF7CB342),
        updatedAt: now,
        history: const <double>[22.2, 22.8, 23.1, 24.4, 24.9, 25.0, 25.8],
      ),
      _price(
        cropId: 'limon',
        cropName: 'Limón',
        variety: 'con semilla',
        market: _market('casa_pueblo'),
        price: 24.1,
        day: 1.1,
        week: 4.9,
        presentation: 'Caja 18 kg',
        color: const Color(0xFF7CB342),
        updatedAt: now,
        history: const <double>[22.0, 22.2, 22.6, 23.0, 23.4, 23.9, 24.1],
      ),
      _price(
        cropId: 'limon',
        cropName: 'Limón',
        variety: 'sin semilla',
        market: _market('oxkutzcab'),
        price: 24.6,
        day: 1.7,
        week: 5.6,
        presentation: 'Caja 18 kg',
        color: const Color(0xFF7CB342),
        updatedAt: now,
        history: const <double>[21.9, 22.4, 22.8, 23.2, 23.8, 24.2, 24.6],
      ),
      _price(
        cropId: 'papaya',
        cropName: 'Papaya',
        variety: 'Maradol',
        market: _market('oxkutzcab'),
        price: 17.9,
        day: -0.6,
        week: 3.2,
        presentation: 'Kilogramo',
        color: const Color(0xFFF97316),
        updatedAt: now,
        history: const <double>[17.0, 17.1, 17.3, 17.5, 17.8, 18.0, 17.9],
      ),
      _price(
        cropId: 'papaya',
        cropName: 'Papaya',
        variety: 'Maradol',
        market: _market('casa_pueblo'),
        price: 18.0,
        day: 0.4,
        week: 3.8,
        presentation: 'Kilogramo',
        color: const Color(0xFFF97316),
        updatedAt: now,
        history: const <double>[17.2, 17.3, 17.4, 17.6, 17.7, 17.9, 18.0],
      ),
      _price(
        cropId: 'papaya',
        cropName: 'Papaya',
        variety: 'Maradol',
        market: _market('merida'),
        price: 18.4,
        day: -1.2,
        week: 4.8,
        presentation: 'Kilogramo',
        color: const Color(0xFFF97316),
        updatedAt: now,
        history: const <double>[17.1, 17.5, 17.9, 18.8, 18.7, 18.6, 18.4],
      ),
      _price(
        cropId: 'tomate',
        cropName: 'Tomate',
        variety: 'saladette',
        market: _market('oxkutzcab'),
        price: 18.7,
        day: -0.4,
        week: -2.2,
        presentation: 'Caja 13 kg',
        color: const Color(0xFFE53935),
        updatedAt: now,
        history: const <double>[19.2, 19.1, 19.0, 18.9, 18.8, 18.8, 18.7],
      ),
      _price(
        cropId: 'tomate',
        cropName: 'Tomate',
        variety: 'bola',
        market: _market('casa_pueblo'),
        price: 20.1,
        day: 1.0,
        week: -0.8,
        presentation: 'Caja 13 kg',
        color: const Color(0xFFE53935),
        updatedAt: now,
        history: const <double>[20.3, 20.2, 20.3, 20.0, 19.9, 19.9, 20.1],
      ),
      _price(
        cropId: 'papaya',
        cropName: 'Papaya',
        variety: 'Maradol',
        market: _market('cancun'),
        price: 21.2,
        day: 2.9,
        week: 7.4,
        presentation: 'Kilogramo',
        color: const Color(0xFFF97316),
        updatedAt: now,
        history: const <double>[19.0, 19.2, 19.8, 20.1, 20.5, 20.6, 21.2],
      ),
      _price(
        cropId: 'maiz',
        cropName: 'Maíz',
        variety: 'blanco',
        market: _market('casa_pueblo'),
        price: 8.7,
        day: 0.2,
        week: 1.9,
        presentation: 'Bulto 50 kg',
        color: const Color(0xFFEAB308),
        updatedAt: now,
        history: const <double>[8.5, 8.5, 8.6, 8.6, 8.7, 8.7, 8.7],
      ),
      _price(
        cropId: 'maiz',
        cropName: 'Maíz',
        variety: 'amarillo',
        market: _market('ticul'),
        price: 8.4,
        day: 0.0,
        week: 1.1,
        presentation: 'Bulto 50 kg',
        color: const Color(0xFFEAB308),
        updatedAt: now,
        history: const <double>[8.3, 8.3, 8.3, 8.4, 8.4, 8.4, 8.4],
      ),
      _price(
        cropId: 'tomate',
        cropName: 'Tomate',
        variety: 'saladette',
        market: _market('merida'),
        price: 19.6,
        day: 0.8,
        week: -3.1,
        presentation: 'Caja 13 kg',
        color: const Color(0xFFE53935),
        updatedAt: now,
        history: const <double>[20.2, 20.4, 20.1, 19.9, 19.5, 19.4, 19.6],
      ),
      _price(
        cropId: 'chile',
        cropName: 'Chile',
        variety: 'habanero primera',
        market: _market('merida'),
        price: 74.2,
        day: 3.1,
        week: 10.4,
        presentation: 'Caja 10 kg',
        color: const Color(0xFFFF9800),
        updatedAt: now,
        history: const <double>[66.4, 67.8, 68.9, 70.2, 72.1, 72.8, 74.2],
      ),
      _price(
        cropId: 'chile',
        cropName: 'Chile',
        variety: 'habanero primera',
        market: _market('ticul'),
        price: 71.3,
        day: 1.8,
        week: 8.9,
        presentation: 'Caja 10 kg',
        color: const Color(0xFFFF9800),
        updatedAt: now,
        history: const <double>[65.5, 66.0, 66.8, 68.1, 69.2, 70.0, 71.3],
      ),
      _price(
        cropId: 'tomate',
        cropName: 'Tomate',
        variety: 'saladette',
        market: _market('iztapalapa'),
        price: 22.8,
        day: 2.2,
        week: 1.5,
        presentation: 'Caja 13 kg',
        color: const Color(0xFFE53935),
        updatedAt: now,
        history: const <double>[21.6, 21.8, 21.9, 22.1, 22.0, 22.3, 22.8],
      ),
      _price(
        cropId: 'sandia',
        cropName: 'Sandía',
        variety: 'rayada',
        market: _market('valladolid'),
        price: 9.4,
        day: -1.4,
        week: -3.8,
        presentation: 'Kilogramo',
        color: const Color(0xFF43A047),
        updatedAt: now,
        history: const <double>[9.8, 9.8, 9.7, 9.6, 9.5, 9.5, 9.4],
      ),
      _price(
        cropId: 'maiz',
        cropName: 'Maíz',
        variety: 'blanco',
        market: _market('merida'),
        price: 8.9,
        day: 0.0,
        week: 2.4,
        presentation: 'Bulto 50 kg',
        color: const Color(0xFFEAB308),
        updatedAt: now,
        history: const <double>[8.6, 8.6, 8.7, 8.7, 8.8, 8.9, 8.9],
      ),
      _price(
        cropId: 'maiz',
        cropName: 'Maíz',
        variety: 'blanco',
        market: _market('guadalajara'),
        price: 9.4,
        day: 1.1,
        week: 3.3,
        presentation: 'Bulto 50 kg',
        color: const Color(0xFFEAB308),
        updatedAt: now,
        history: const <double>[9.0, 9.0, 9.1, 9.2, 9.2, 9.3, 9.4],
      ),
      _price(
        cropId: 'chile',
        cropName: 'Chile',
        variety: 'habanero primera',
        market: _market('oxkutzcab'),
        price: 72.5,
        day: 4.2,
        week: 11.6,
        presentation: 'Caja 10 kg',
        color: const Color(0xFFFF9800),
        updatedAt: now,
        history: const <double>[62.8, 64.2, 65.1, 67.6, 69.8, 70.2, 72.5],
      ),
      _price(
        cropId: 'chile',
        cropName: 'Chile',
        variety: 'habanero primera',
        market: _market('cancun'),
        price: 76.9,
        day: 2.6,
        week: 9.8,
        presentation: 'Caja 10 kg',
        color: const Color(0xFFFF9800),
        updatedAt: now,
        history: const <double>[69.0, 69.5, 70.8, 72.1, 73.5, 75.0, 76.9],
      ),
      _price(
        cropId: 'sandia',
        cropName: 'Sandía',
        variety: 'rayada',
        market: _market('merida'),
        price: 9.8,
        day: -2.0,
        week: -5.2,
        presentation: 'Kilogramo',
        color: const Color(0xFF43A047),
        updatedAt: now,
        history: const <double>[10.4, 10.3, 10.2, 10.0, 9.9, 10.0, 9.8],
      ),
      _price(
        cropId: 'aguacate',
        cropName: 'Aguacate',
        variety: 'Hass',
        market: _market('iztapalapa'),
        price: 68.3,
        day: 1.4,
        week: 6.2,
        presentation: 'Caja 10 kg',
        color: const Color(0xFF558B2F),
        updatedAt: now,
        history: const <double>[63.4, 64.0, 64.8, 66.2, 66.7, 67.4, 68.3],
      ),
      _price(
        cropId: 'mango',
        cropName: 'Mango',
        variety: 'Ataulfo',
        market: _market('campeche'),
        price: 31.7,
        day: 3.1,
        week: 9.2,
        presentation: 'Caja 25 kg',
        color: const Color(0xFFFFB300),
        updatedAt: now,
        history: const <double>[28.2, 28.8, 29.1, 29.9, 30.4, 30.8, 31.7],
      ),
    ];
  }

  static MarketCenter _market(String id) {
    return _markets.firstWhere((market) => market.id == id);
  }

  static CropMarketPrice _price({
    required String cropId,
    required String cropName,
    required String variety,
    required MarketCenter market,
    required double price,
    required double day,
    required double week,
    required String presentation,
    required Color color,
    required DateTime updatedAt,
    required List<double> history,
  }) {
    return CropMarketPrice(
      cropId: cropId,
      cropName: cropName,
      variety: variety,
      market: market,
      pricePerKg: price,
      dailyChangePercent: day,
      weeklyChangePercent: week,
      presentation: presentation,
      quality: 'Primera',
      updatedAt: updatedAt,
      source: 'Referencia local SNIIM/SIAP',
      color: color,
      history: List<MarketPricePoint>.generate(history.length, (index) {
        return MarketPricePoint(
          date: updatedAt.subtract(Duration(days: history.length - index - 1)),
          pricePerKg: history[index],
        );
      }),
    );
  }
}
