import 'package:flutter/material.dart';

import '../models/crop_catalog_item.dart';

class CropCatalogService {
  const CropCatalogService._();

  static final List<CropCatalogItem> items = <CropCatalogItem>[
    _crop(
      id: 'maiz',
      name: 'Maíz',
      season: 'Primavera - Verano',
      sowingWindow: 'Abril - Junio',
      harvestWindow: 'Agosto - Octubre',
      cycleDays: 140,
      description:
          'Cultivo base de la agricultura mexicana, adaptable a muchas regiones.',
      fertilizers: const <String>[
        'Nitrógeno (N): 120-150 kg/ha',
        'Fósforo (P₂O₅): 60-80 kg/ha',
        'Potasio (K₂O): 40-60 kg/ha',
      ],
      pests: const <String>[
        'Gusano cogollero',
        'Barrenador del tallo',
        'Gallina ciega',
      ],
      colorA: const Color(0xFFFBBF24),
      colorB: const Color(0xFFEAB308),
      icon: Icons.grass_rounded,
      pdfAssetPath: 'assets/pdfs/maiz_ficha_tecnica.pdf',
      idealTemperature: '24-32 °C',
      waterRequirement: '500-800 mm por ciclo',
      soilType: 'Franco a franco-arcilloso, bien drenado',
      soilPh: '5.5 - 7.5',
      plantingDensity: '55,000-75,000 plantas/ha',
      expectedYield: '4-10 t/ha de grano',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'frijol',
      name: 'Frijol',
      season: 'Primavera - Verano',
      sowingWindow: 'Junio - Agosto',
      harvestWindow: 'Septiembre - Noviembre',
      cycleDays: 95,
      description:
          'Leguminosa esencial en México; mejora el suelo y requiere buen drenaje.',
      fertilizers: const <String>[
        'Inoculación con rizobio cuando sea posible',
        'Fósforo (P₂O₅): 40-60 kg/ha',
        'Potasio (K₂O): 30-50 kg/ha',
      ],
      pests: const <String>['Mosca blanca', 'Conchuela', 'Antracnosis'],
      colorA: const Color(0xFF7C3F23),
      colorB: const Color(0xFF4B2416),
      icon: Icons.eco_rounded,
      idealTemperature: '18-28 °C',
      waterRequirement: '300-500 mm por ciclo',
      soilType: 'Franco, suelto y con drenaje rápido',
      soilPh: '6.0 - 7.5',
      plantingDensity: '180,000-250,000 plantas/ha',
      expectedYield: '1-2.5 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'trigo',
      name: 'Trigo',
      season: 'Otoño - Invierno',
      sowingWindow: 'Noviembre - Enero',
      harvestWindow: 'Marzo - Mayo',
      cycleDays: 125,
      description:
          'Cereal de clima templado con alta importancia alimentaria e industrial.',
      fertilizers: const <String>[
        'Nitrógeno (N): 100-140 kg/ha',
        'Fósforo (P₂O₅): 50-70 kg/ha',
        'Potasio (K₂O): 20-40 kg/ha',
      ],
      pests: const <String>[
        'Pulgón del trigo',
        'Roya amarilla',
        'Carbón parcial',
      ],
      colorA: const Color(0xFFD97706),
      colorB: const Color(0xFFB45309),
      icon: Icons.agriculture_rounded,
      pdfAssetPath: 'assets/pdfs/trigo_ficha_tecnica.pdf',
      idealTemperature: '12-24 °C',
      waterRequirement: '450-650 mm por ciclo',
      soilType: 'Franco con buena retención y drenaje',
      soilPh: '6.0 - 7.5',
      plantingDensity: '180-250 kg de semilla/ha',
      expectedYield: '3-8 t/ha',
      sunExposure: 'Sol directo',
    ),
    _crop(
      id: 'sorgo',
      name: 'Sorgo',
      season: 'Verano - Otoño',
      sowingWindow: 'Junio - Agosto',
      harvestWindow: 'Octubre - Diciembre',
      cycleDays: 105,
      description:
          'Alternativa resistente a estrés hídrico para grano o forraje.',
      fertilizers: const <String>[
        'Nitrógeno (N): 90-120 kg/ha',
        'Fósforo (P₂O₅): 40-60 kg/ha',
        'Potasio (K₂O): 30-50 kg/ha',
      ],
      pests: const <String>[
        'Mosquita del sorgo',
        'Pulgón amarillo',
        'Gusano cogollero',
      ],
      colorA: const Color(0xFFF97316),
      colorB: const Color(0xFFEA580C),
      icon: Icons.park_rounded,
      pdfAssetPath: 'assets/pdfs/sorgo_ficha_tecnica.pdf',
      idealTemperature: '26-34 °C',
      waterRequirement: '350-550 mm por ciclo',
      soilType: 'Franco a arcilloso, tolera menor fertilidad',
      soilPh: '5.5 - 8.0',
      plantingDensity: '120,000-180,000 plantas/ha',
      expectedYield: '3-7 t/ha de grano',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'cana_de_azucar',
      name: 'Caña de azúcar',
      imageName: 'cana de azucar',
      season: 'Todo el año',
      sowingWindow: 'Octubre - Marzo',
      harvestWindow: '12-18 meses después de siembra',
      cycleDays: 450,
      description:
          'Cultivo industrial de zonas cálidas, demandante de agua y nutrición.',
      fertilizers: const <String>[
        'Nitrógeno (N): 120-180 kg/ha',
        'Fósforo (P₂O₅): 60-90 kg/ha',
        'Potasio (K₂O): 120-200 kg/ha',
      ],
      pests: const <String>[
        'Barrenador de la caña',
        'Salivazo',
        'Rata de campo',
      ],
      colorA: const Color(0xFF84CC16),
      colorB: const Color(0xFF4D7C0F),
      icon: Icons.forest_rounded,
      idealTemperature: '24-32 °C',
      waterRequirement: '1,500-2,500 mm por ciclo',
      soilType: 'Profundo, fértil y con buena humedad',
      soilPh: '6.0 - 8.0',
      plantingDensity: '8-12 t de semilla/ha',
      expectedYield: '70-120 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'aguacate',
      name: 'Aguacate',
      season: 'Perenne',
      sowingWindow: 'Junio - Agosto',
      harvestWindow: 'Variable según variedad',
      cycleDays: 365,
      description:
          'Frutal de alto valor que exige suelo profundo, drenaje y manejo sanitario.',
      fertilizers: const <String>[
        'Nitrógeno fraccionado según edad del árbol',
        'Calcio, zinc y boro en monitoreo foliar',
        'Materia orgánica para mejorar estructura',
      ],
      pests: const <String>['Trips', 'Barrenador de ramas', 'Araña roja'],
      colorA: const Color(0xFF65A30D),
      colorB: const Color(0xFF166534),
      icon: Icons.emoji_nature_rounded,
      idealTemperature: '18-26 °C',
      waterRequirement: '800-1,200 mm/año',
      soilType: 'Profundo, franco arenoso y muy bien drenado',
      soilPh: '5.5 - 7.0',
      plantingDensity: '200-400 árboles/ha',
      expectedYield: '8-18 t/ha',
      sunExposure: 'Alta radiación sin heladas',
    ),
    _crop(
      id: 'tomate',
      name: 'Tomate',
      season: 'Todo el año',
      sowingWindow: 'Todo el año bajo riego',
      harvestWindow: '75-90 días después de trasplante',
      cycleDays: 110,
      description:
          'Hortaliza de alto valor comercial con manejo intensivo de riego y sanidad.',
      fertilizers: const <String>[
        'Nitrógeno (N): 150-200 kg/ha',
        'Fósforo (P₂O₅): 100-150 kg/ha',
        'Potasio (K₂O): 200-250 kg/ha',
      ],
      pests: const <String>[
        'Mosca blanca',
        'Gusano del fruto',
        'Araña roja',
        'Trips',
      ],
      colorA: const Color(0xFFF87171),
      colorB: const Color(0xFFDC2626),
      icon: Icons.local_florist_rounded,
      pdfAssetPath: 'assets/pdfs/tomate_ficha_tecnica.pdf',
      idealTemperature: '18-28 °C',
      waterRequirement: '600-900 mm por ciclo',
      soilType: 'Franco arenoso, profundo y drenado',
      soilPh: '6.0 - 7.0',
      plantingDensity: '10,000-18,000 plantas/ha',
      expectedYield: '30-80 t/ha',
      sunExposure: 'Alta radiación y buena ventilación',
    ),
    _crop(
      id: 'chile',
      name: 'Chile',
      season: 'Primavera - Verano',
      sowingWindow: 'Febrero - Mayo',
      harvestWindow: '70-120 días después de trasplante',
      cycleDays: 130,
      description:
          'Hortaliza clave para el mercado nacional, sensible a estrés hídrico.',
      fertilizers: const <String>[
        'Nitrógeno (N): 140-180 kg/ha',
        'Fósforo (P₂O₅): 80-120 kg/ha',
        'Potasio (K₂O): 160-220 kg/ha',
      ],
      pests: const <String>['Picudo del chile', 'Trips', 'Mosca blanca'],
      colorA: const Color(0xFFEF4444),
      colorB: const Color(0xFF991B1B),
      icon: Icons.local_fire_department_rounded,
      idealTemperature: '20-30 °C',
      waterRequirement: '500-800 mm por ciclo',
      soilType: 'Franco arenoso con drenaje',
      soilPh: '6.0 - 7.0',
      plantingDensity: '20,000-35,000 plantas/ha',
      expectedYield: '12-35 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'limon',
      name: 'Limón',
      season: 'Perenne',
      sowingWindow: 'Junio - Septiembre',
      harvestWindow: 'Todo el año con picos por región',
      cycleDays: 365,
      description:
          'Cítrico productivo en zonas cálidas, con demanda constante de nutrición.',
      fertilizers: const <String>[
        'Nitrógeno fraccionado según producción',
        'Potasio alto durante llenado de fruto',
        'Micronutrientes: zinc, hierro y manganeso',
      ],
      pests: const <String>['Minador de la hoja', 'Psílido asiático', 'Ácaros'],
      colorA: const Color(0xFFA3E635),
      colorB: const Color(0xFF65A30D),
      icon: Icons.circle_rounded,
      idealTemperature: '22-32 °C',
      waterRequirement: '900-1,200 mm/año',
      soilType: 'Franco, profundo y bien drenado',
      soilPh: '6.0 - 7.5',
      plantingDensity: '250-500 árboles/ha',
      expectedYield: '12-30 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'naranja',
      name: 'Naranja',
      season: 'Perenne',
      sowingWindow: 'Junio - Septiembre',
      harvestWindow: 'Noviembre - Mayo',
      cycleDays: 365,
      description:
          'Cítrico de amplia distribución, sensible a encharcamientos y plagas.',
      fertilizers: const <String>[
        'Nitrógeno fraccionado en brotación',
        'Potasio para calidad de fruto',
        'Materia orgánica anual',
      ],
      pests: const <String>['Psílido asiático', 'Mosca de la fruta', 'Ácaros'],
      colorA: const Color(0xFFFFB020),
      colorB: const Color(0xFFF97316),
      icon: Icons.circle_outlined,
      idealTemperature: '18-32 °C',
      waterRequirement: '800-1,200 mm/año',
      soilType: 'Franco profundo, sin compactación',
      soilPh: '6.0 - 7.5',
      plantingDensity: '250-400 árboles/ha',
      expectedYield: '15-35 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'mango',
      name: 'Mango',
      season: 'Perenne',
      sowingWindow: 'Inicio de lluvias',
      harvestWindow: 'Marzo - Agosto',
      cycleDays: 365,
      description:
          'Frutal tropical tolerante a calor, requiere poda y manejo de floración.',
      fertilizers: const <String>[
        'Nitrógeno moderado después de cosecha',
        'Potasio y calcio durante fruto',
        'Boro y zinc en etapa reproductiva',
      ],
      pests: const <String>['Mosca de la fruta', 'Antracnosis', 'Escamas'],
      colorA: const Color(0xFFFACC15),
      colorB: const Color(0xFFF97316),
      icon: Icons.yard_rounded,
      idealTemperature: '24-34 °C',
      waterRequirement: '700-1,200 mm/año',
      soilType: 'Profundo, aireado y bien drenado',
      soilPh: '5.5 - 7.5',
      plantingDensity: '100-250 árboles/ha',
      expectedYield: '8-20 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'cafe',
      name: 'Café',
      season: 'Perenne',
      sowingWindow: 'Mayo - Julio',
      harvestWindow: 'Octubre - Marzo',
      cycleDays: 365,
      description:
          'Cultivo de zonas altas y húmedas que se beneficia de sombra regulada.',
      fertilizers: const <String>[
        'Nitrógeno fraccionado después de lluvias',
        'Fósforo para establecimiento',
        'Potasio para llenado de grano',
      ],
      pests: const <String>['Broca del café', 'Roya', 'Minador de la hoja'],
      colorA: const Color(0xFF8B5E34),
      colorB: const Color(0xFF3F2A1D),
      icon: Icons.coffee_rounded,
      idealTemperature: '18-24 °C',
      waterRequirement: '1,200-1,800 mm/año',
      soilType: 'Profundo, rico en materia orgánica',
      soilPh: '5.0 - 6.5',
      plantingDensity: '3,000-5,000 plantas/ha',
      expectedYield: '1-3 t/ha de café pergamino',
      sunExposure: 'Sombra parcial',
    ),
    _crop(
      id: 'agave',
      name: 'Agave',
      season: 'Perenne',
      sowingWindow: 'Junio - Septiembre',
      harvestWindow: '5-7 años después de plantación',
      cycleDays: 2190,
      description:
          'Cultivo resistente a sequía para regiones semiáridas y suelos ligeros.',
      fertilizers: const <String>[
        'Materia orgánica en establecimiento',
        'Nitrógeno moderado en crecimiento',
        'Evitar excesos de humedad y sales',
      ],
      pests: const <String>['Picudo del agave', 'Escama', 'Pudriciones'],
      colorA: const Color(0xFF2DD4BF),
      colorB: const Color(0xFF0F766E),
      icon: Icons.spa_rounded,
      idealTemperature: '18-30 °C',
      waterRequirement: '300-600 mm/año',
      soilType: 'Franco arenoso, pedregoso y drenado',
      soilPh: '6.0 - 8.0',
      plantingDensity: '2,000-3,500 plantas/ha',
      expectedYield: '80-140 t/ha de piña',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'papa',
      name: 'Papa',
      season: 'Otoño - Invierno',
      sowingWindow: 'Octubre - Febrero',
      harvestWindow: '90-120 días después de siembra',
      cycleDays: 115,
      description:
          'Tubérculo de clima fresco que exige suelo suelto y humedad uniforme.',
      fertilizers: const <String>[
        'Nitrógeno (N): 120-180 kg/ha',
        'Fósforo (P₂O₅): 120-180 kg/ha',
        'Potasio (K₂O): 180-250 kg/ha',
      ],
      pests: const <String>[
        'Tizón tardío',
        'Palomilla de la papa',
        'Nematodos',
      ],
      colorA: const Color(0xFFD6A85C),
      colorB: const Color(0xFF9A6B2F),
      icon: Icons.egg_alt_rounded,
      idealTemperature: '15-22 °C',
      waterRequirement: '500-700 mm por ciclo',
      soilType: 'Franco arenoso, profundo y suelto',
      soilPh: '5.5 - 6.5',
      plantingDensity: '35,000-50,000 plantas/ha',
      expectedYield: '25-45 t/ha',
      sunExposure: 'Sol directo en clima fresco',
    ),
    _crop(
      id: 'cebolla',
      name: 'Cebolla',
      season: 'Otoño - Invierno',
      sowingWindow: 'Septiembre - Enero',
      harvestWindow: '120-160 días después de siembra',
      cycleDays: 145,
      description:
          'Hortaliza de bulbo sensible a malezas y a exceso de humedad.',
      fertilizers: const <String>[
        'Nitrógeno (N): 100-140 kg/ha',
        'Fósforo (P₂O₅): 80-120 kg/ha',
        'Potasio (K₂O): 120-180 kg/ha',
      ],
      pests: const <String>['Trips', 'Mildiu', 'Pudrición blanca'],
      colorA: const Color(0xFFF8DFA6),
      colorB: const Color(0xFFB45309),
      icon: Icons.radio_button_unchecked_rounded,
      idealTemperature: '13-24 °C',
      waterRequirement: '350-550 mm por ciclo',
      soilType: 'Franco arenoso, suelto y drenado',
      soilPh: '6.0 - 7.2',
      plantingDensity: '350,000-600,000 plantas/ha',
      expectedYield: '25-60 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'pepino',
      name: 'Pepino',
      season: 'Primavera - Verano',
      sowingWindow: 'Febrero - Agosto',
      harvestWindow: '45-60 días después de siembra',
      cycleDays: 65,
      description:
          'Cucurbitácea de ciclo corto, productiva con riego constante.',
      fertilizers: const <String>[
        'Nitrógeno (N): 100-150 kg/ha',
        'Fósforo (P₂O₅): 60-100 kg/ha',
        'Potasio (K₂O): 120-180 kg/ha',
      ],
      pests: const <String>['Mosca blanca', 'Mildiu', 'Pulgones'],
      colorA: const Color(0xFF22C55E),
      colorB: const Color(0xFF15803D),
      icon: Icons.water_drop_rounded,
      idealTemperature: '22-30 °C',
      waterRequirement: '400-600 mm por ciclo',
      soilType: 'Franco arenoso con materia orgánica',
      soilPh: '6.0 - 7.0',
      plantingDensity: '12,000-20,000 plantas/ha',
      expectedYield: '25-60 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'sandia',
      name: 'Sandía',
      season: 'Primavera - Verano',
      sowingWindow: 'Febrero - Mayo',
      harvestWindow: '75-95 días después de siembra',
      cycleDays: 90,
      description:
          'Fruto de clima cálido que requiere espacio, polinización y buen drenaje.',
      fertilizers: const <String>[
        'Nitrógeno (N): 100-140 kg/ha',
        'Fósforo (P₂O₅): 60-90 kg/ha',
        'Potasio (K₂O): 140-220 kg/ha',
      ],
      pests: const <String>['Mosca blanca', 'Trips', 'Mildiu'],
      colorA: const Color(0xFFEF4444),
      colorB: const Color(0xFF16A34A),
      icon: Icons.album_rounded,
      idealTemperature: '24-34 °C',
      waterRequirement: '400-650 mm por ciclo',
      soilType: 'Franco arenoso, profundo y cálido',
      soilPh: '6.0 - 7.0',
      plantingDensity: '3,000-6,000 plantas/ha',
      expectedYield: '25-50 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'papaya',
      name: 'Papaya',
      season: 'Todo el año',
      sowingWindow: 'Inicio de lluvias o bajo riego',
      harvestWindow: '8-10 meses después de trasplante',
      cycleDays: 300,
      description:
          'Frutal tropical de rápido crecimiento, sensible a encharcamientos.',
      fertilizers: const <String>[
        'Nitrógeno y potasio fraccionados',
        'Calcio y boro durante floración',
        'Materia orgánica en establecimiento',
      ],
      pests: const <String>[
        'Ácaros',
        'Mosca blanca',
        'Virus de la mancha anular',
      ],
      colorA: const Color(0xFFFFB86B),
      colorB: const Color(0xFFF97316),
      icon: Icons.filter_vintage_rounded,
      idealTemperature: '22-32 °C',
      waterRequirement: '1,000-1,500 mm/año',
      soilType: 'Profundo, ligero y muy drenado',
      soilPh: '6.0 - 7.0',
      plantingDensity: '1,600-2,500 plantas/ha',
      expectedYield: '40-90 t/ha',
      sunExposure: 'Pleno sol y sin vientos fuertes',
    ),
    _crop(
      id: 'platano',
      name: 'Plátano',
      season: 'Todo el año',
      sowingWindow: 'Inicio de lluvias o bajo riego',
      harvestWindow: '10-14 meses después de plantación',
      cycleDays: 360,
      description: 'Cultivo tropical de alta demanda hídrica y nutricional.',
      fertilizers: const <String>[
        'Nitrógeno (N): 180-250 kg/ha/año',
        'Potasio (K₂O): 300-450 kg/ha/año',
        'Magnesio y zinc según análisis',
      ],
      pests: const <String>['Sigatoka negra', 'Picudo negro', 'Nematodos'],
      colorA: const Color(0xFFFDE047),
      colorB: const Color(0xFF84CC16),
      icon: Icons.energy_savings_leaf_rounded,
      idealTemperature: '24-32 °C',
      waterRequirement: '1,500-2,500 mm/año',
      soilType: 'Profundo, fértil y con drenaje',
      soilPh: '5.5 - 7.0',
      plantingDensity: '1,600-2,000 plantas/ha',
      expectedYield: '30-70 t/ha',
      sunExposure: 'Pleno sol con protección contra viento',
    ),
    _crop(
      id: 'arroz',
      name: 'Arroz',
      season: 'Primavera - Verano',
      sowingWindow: 'Mayo - Julio',
      harvestWindow: 'Septiembre - Noviembre',
      cycleDays: 130,
      description:
          'Cereal de alta demanda de agua, productivo en zonas cálidas y niveladas.',
      fertilizers: const <String>[
        'Nitrógeno (N): 100-160 kg/ha',
        'Fósforo (P₂O₅): 40-80 kg/ha',
        'Potasio (K₂O): 40-80 kg/ha',
      ],
      pests: const <String>[
        'Chinche del arroz',
        'Piricularia',
        'Malezas acuáticas',
      ],
      colorA: const Color(0xFFE5E7EB),
      colorB: const Color(0xFF94A3B8),
      icon: Icons.grain_rounded,
      idealTemperature: '24-32 °C',
      waterRequirement: '1,000-1,500 mm por ciclo',
      soilType: 'Arcilloso a franco arcilloso, nivelado',
      soilPh: '5.5 - 7.0',
      plantingDensity: '80-120 kg de semilla/ha',
      expectedYield: '4-8 t/ha',
      sunExposure: 'Pleno sol',
    ),
    _crop(
      id: 'zanahoria',
      name: 'Zanahoria',
      season: 'Invierno - Primavera',
      sowingWindow: 'Octubre - Febrero',
      harvestWindow: 'Enero - Mayo',
      cycleDays: 100,
      description:
          'Raíz de ciclo corto que demanda suelo suelto y humedad uniforme.',
      fertilizers: const <String>[
        'Nitrógeno (N): 80-100 kg/ha',
        'Fósforo (P₂O₅): 60-80 kg/ha',
        'Potasio (K₂O): 120-150 kg/ha',
      ],
      pests: const <String>['Mosca de la zanahoria', 'Nematodos', 'Alternaria'],
      colorA: const Color(0xFFF97316),
      colorB: const Color(0xFFEA580C),
      icon: Icons.spa_rounded,
      pdfAssetPath: 'assets/pdfs/zanahoria_ficha_tecnica.pdf',
      idealTemperature: '15-22 °C',
      waterRequirement: '350-500 mm por ciclo',
      soilType: 'Suelto, profundo, franco arenoso',
      soilPh: '6.0 - 6.8',
      plantingDensity: '0.8-1.2 millones de plantas/ha',
      expectedYield: '25-45 t/ha',
      sunExposure: 'Sol completo',
    ),
    _crop(
      id: 'soja',
      name: 'Soja',
      season: 'Primavera - Verano',
      sowingWindow: 'Mayo - Julio',
      harvestWindow: 'Septiembre - Noviembre',
      cycleDays: 115,
      description:
          'Leguminosa con buena fijación de nitrógeno y demanda de monitoreo sanitario.',
      fertilizers: const <String>[
        'Inoculante de rizobio',
        'Fósforo (P₂O₅): 50-70 kg/ha',
        'Potasio (K₂O): 60-90 kg/ha',
      ],
      pests: const <String>['Chinche verde', 'Oruga medidora', 'Roya asiática'],
      colorA: const Color(0xFF16A34A),
      colorB: const Color(0xFF15803D),
      icon: Icons.eco_rounded,
      pdfAssetPath: 'assets/pdfs/soja_ficha_tecnica.pdf',
      idealTemperature: '20-30 °C',
      waterRequirement: '450-700 mm por ciclo',
      soilType: 'Franco a franco-arcilloso bien drenado',
      soilPh: '6.0 - 7.0',
      plantingDensity: '250,000-400,000 plantas/ha',
      expectedYield: '2.5-4.5 t/ha',
      sunExposure: 'Alta radiación',
    ),
  ];

  static CropCatalogItem byId(String id) {
    return items.firstWhere((item) => item.id == id, orElse: () => items.first);
  }

  static CropCatalogItem _crop({
    required String id,
    required String name,
    required String season,
    required String sowingWindow,
    required String harvestWindow,
    required int cycleDays,
    required String description,
    required List<String> fertilizers,
    required List<String> pests,
    required Color colorA,
    required Color colorB,
    required IconData icon,
    required String idealTemperature,
    required String waterRequirement,
    required String soilType,
    required String soilPh,
    required String plantingDensity,
    required String expectedYield,
    required String sunExposure,
    String? pdfAssetPath,
    String? imageName,
  }) {
    return CropCatalogItem(
      id: id,
      name: name,
      imageAsset: 'assets/images/CUL - ${imageName ?? id}.png',
      season: season,
      sowingWindow: sowingWindow,
      harvestWindow: harvestWindow,
      cycleDays: cycleDays,
      description: description,
      fertilizers: fertilizers,
      pests: pests,
      gradientColors: <Color>[colorA, colorB],
      badgeColor: colorB,
      icon: icon,
      pdfAssetPath: pdfAssetPath,
      idealTemperature: idealTemperature,
      waterRequirement: waterRequirement,
      soilType: soilType,
      soilPh: soilPh,
      plantingDensity: plantingDensity,
      expectedYield: expectedYield,
      sunExposure: sunExposure,
    );
  }
}
